"""Solidity file generation for merge_invariants package."""
import re
from datetime import datetime, timezone
from pathlib import Path

from merge.constants import _PRAGMA


def generate_hunter_sol_file(
    hunter_suffix: str,
    base_contract: str,
    ghosts: list[str],
    properties: list[str],
    optimizes: list[str],
    component: str,
    pragma: str = _PRAGMA,
) -> str:
    """Genera el contenido completo de un archivo PropertiesX.sol."""
    contract_name = f"Properties{hunter_suffix}"
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        "// SPDX-License-Identifier: UNLICENSED",
        pragma,
        "",
        f'import "./{base_contract}.sol";',
        "",
        f"/// @title {component} {hunter_suffix} Hunter Invariants",
        f"/// @notice Auto-generated by merge_invariants.py ({date_str})",
        f"/// @dev Inherits {base_contract} for ghost vars and setup access",
        f"abstract contract {contract_name} is {base_contract} {{",
        "",
    ]

    # Ghost variables
    if ghosts:
        lines.append(f"    // ======= GHOST VARIABLES ({hunter_suffix}Hunter) =======")
        lines.append("")
        lines.extend(ghosts)
        lines.append("")

    # Property invariants
    if properties:
        lines.append(f"    // ======= PROPERTY INVARIANTS ({hunter_suffix}Hunter) =======")
        lines.append("")
        lines.extend(f"{p}\n" for p in properties)

    # Optimization functions
    if optimizes:
        lines.append(f"    // ======= OPTIMIZATION FUNCTIONS ({hunter_suffix}Hunter) =======")
        lines.append("")
        lines.extend(f"{o}\n" for o in optimizes)

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def generate_cross_component_sol_file(
    ghosts: list[str],
    properties: list[str],
    optimizes: list[str],
    components: list[str],
    pragma: str = _PRAGMA,
) -> str:
    """
    Genera PropertiesCross.sol para invariantes cross-component.
    A diferencia de los PropertiesX.sol normales, este NO hereda de Properties
    (que tiene setup de un solo contrato). En su lugar, declara variables de estado
    para los contratos involucrados que se setean en el setup del test.
    """
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    comp_label = " + ".join(components)

    lines = [
        "// SPDX-License-Identifier: UNLICENSED",
        pragma,
        "",
        f"/// @title Cross-Component Invariants: {comp_label}",
        f"/// @notice Auto-generated by merge_invariants.py ({date_str})",
        f"/// @dev EdgeHunter output. Setup must deploy all referenced contracts.",
        f"/// @dev Inherits nothing — setup function must initialize contract refs.",
        "abstract contract PropertiesCross {",
        "",
        f"    // ======= CROSS-COMPONENT CONTRACT REFERENCES =======",
        f"    // These must be set in the test setup (e.g., CryticTester.setUp())",
        f"    // Example: crossContractA = address(deployedA);",
        "",
    ]

    # Declare address vars for each component
    for i, comp in enumerate(components):
        var_name = f"crossContract{chr(65 + i)}"  # crossContractA, crossContractB, ...
        lines.append(f"    address internal {var_name}; // {comp}")
    lines.append("")

    # Ghost variables
    if ghosts:
        lines.append(f"    // ======= GHOST VARIABLES (EdgeHunter) =======")
        lines.append("")
        lines.extend(ghosts)
        lines.append("")

    # Property invariants
    if properties:
        lines.append(f"    // ======= CROSS-COMPONENT INVARIANTS (EdgeHunter) =======")
        lines.append("")
        lines.extend(f"{p}\n" for p in properties)

    # Optimization functions
    if optimizes:
        lines.append(f"    // ======= OPTIMIZATION FUNCTIONS (EdgeHunter) =======")
        lines.append("")
        lines.extend(f"{o}\n" for o in optimizes)

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def update_target_functions_import(chimera_dir: Path, hunter_suffixes: list,
                                   dry_run: bool = False, pragma: str = _PRAGMA):
    """
    Actualiza TargetFunctions.sol para heredar del contrato agregador
    que incluye todos los PropertiesX.sol.

    En vez de tocar TargetFunctions directamente (que es código del usuario),
    generamos un PropertiesAll.sol intermedio que hereda de todos.
    TargetFunctions hereda de PropertiesAll en vez de Properties.
    """
    all_file = chimera_dir / "PropertiesAll.sol"
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    imports = ['import "./Properties.sol";']
    parents = ["Properties"]

    for suffix in sorted(hunter_suffixes):
        imports.append(f'import "./Properties{suffix}.sol";')
        parents.append(f"Properties{suffix}")

    content = [
        "// SPDX-License-Identifier: UNLICENSED",
        pragma,
        "",
        *imports,
        "",
        f"/// @title Aggregator — inherits base Properties + all per-hunter Properties",
        f"/// @notice Auto-generated by merge_invariants.py ({date_str})",
        f"/// @dev TargetFunctions inherits this instead of Properties directly",
        f"abstract contract PropertiesAll is {', '.join(parents)} {{",
        "",
        "}",
        "",
    ]

    all_content = "\n".join(content)

    if dry_run:
        print(f"\n  [DRY-RUN] Generaría {all_file.name}:")
        print(f"    Herencia: {' → '.join(parents)}")
        return True

    all_file.write_text(all_content)
    print(f"  ✓ {all_file.name} generado (hereda {len(parents)} contratos)")

    # Actualizar TargetFunctions.sol para importar PropertiesAll en vez de Properties
    tf_path = chimera_dir / "TargetFunctions.sol"
    if tf_path.exists():
        tf_text = tf_path.read_text()
        # Solo cambiar si todavía importa Properties directamente
        if 'import "./Properties.sol"' in tf_text and 'import "./PropertiesAll.sol"' not in tf_text:
            tf_text = tf_text.replace(
                'import "./Properties.sol";',
                'import "./PropertiesAll.sol";'
            )
            tf_text = tf_text.replace(
                "is Properties",
                "is PropertiesAll"
            )
            tf_path.write_text(tf_text)
            print(f"  ✓ TargetFunctions.sol actualizado: Properties → PropertiesAll")
        elif 'import "./PropertiesAll.sol"' in tf_text:
            print(f"  ✓ TargetFunctions.sol ya importa PropertiesAll")
        else:
            print(f"  ⚠ TargetFunctions.sol: no se encontró import de Properties")

    return True


def clean_properties_base(chimera_dir: Path, dry_run: bool) -> None:
    """Limpia Properties.sol eliminando invariantes de merges anteriores.

    Mantiene solo el código base (ghost vars + invariantes originales INV-*).
    Todo lo que fue añadido por merge_invariants.py se elimina, ya que ahora
    va en archivos split separados.
    """
    props_path = chimera_dir / "Properties.sol"
    if not props_path.exists():
        return

    text = props_path.read_text()

    # Buscar el marcador de merge_invariants o el primer invariante no-INV
    # El patrón: "// --- Invariantes añadidos por merge_invariants" o
    # "// --- Ghost vars añadidas por merge_invariants ---" (el segundo bloque)
    # Buscar marcadores de invariantes añadidos (NO ghost vars, esas se quedan)
    marker_es = "// --- Invariantes añadidos por merge_invariants"
    marker_en = "// --- Invariants added by merge_invariants"

    cut_pos = -1
    for m in [marker_es, marker_en]:
        pos = text.find(m)
        if pos != -1:
            cut_pos = pos
            break

    if cut_pos == -1:
        # No merge markers — check for non-base property functions (VV-*, AC-*, etc.)
        # Base functions use names like property_solvency, property_debtSharesConsistency, etc.
        # Merge-generated use property_vv_m_01, property_vv_ac_01, etc.
        non_base = re.search(r'\n    function property_vv_\w+\(', text)
        if not non_base:
            non_base = re.search(r'\n    function property_[a-z]{2}_\w+\(', text)
        if non_base:
            cut_pos = non_base.start()

    if cut_pos == -1:
        return  # Properties.sol is already clean

    # Find the last valid line before the cut point
    # We want to keep everything up to the last complete function before the marker
    lines = text[:cut_pos].rstrip().split('\n')

    # Remove trailing empty lines
    while lines and not lines[-1].strip():
        lines.pop()

    # Close the contract
    cleaned = '\n'.join(lines) + '\n\n}\n'
    cleaned += '// NOTE: Hunter-generated invariants are in separate PropertiesX.sol files.\n'
    cleaned += '// See PropertiesAll.sol for the aggregator.\n'

    if dry_run:
        original_lines = text.count('\n')
        cleaned_lines = cleaned.count('\n')
        print(f"  [DRY-RUN] Limpiaría Properties.sol: {original_lines} → {cleaned_lines} líneas")
        return

    props_path.write_text(cleaned)
    original_lines = text.count('\n')
    cleaned_lines = cleaned.count('\n')
    print(f"  ✓ Properties.sol limpiado: {original_lines} → {cleaned_lines} líneas (base only)")
