"""Report generators for audit findings.

Supports multiple output formats:
  - Internal markdown report (default)
  - Code4rena competition submission format
  - Immunefi bug bounty submission format
  - Cantina competition submission format
"""
import json
import os
from datetime import datetime
from pathlib import Path

TEMPLATES_DIR = Path(__file__).parent / "templates"

# ---------------------------------------------------------------------------
# Severity mapping: internal severity -> platform severity
# ---------------------------------------------------------------------------
SEVERITY_MAP_C4 = {
    "CRITICAL": "High",   # C4 has no "Critical"; highest is High (3)
    "HIGH": "High",
    "MEDIUM": "Medium",
    "LOW": "QA",
    "INFO": "QA",
}

SEVERITY_MAP_IMMUNEFI = {
    "CRITICAL": "Critical",
    "HIGH": "High",
    "MEDIUM": "Medium",
    "LOW": "Low",
    "INFO": "Insight",     # Immunefi doesn't pay for these
}

SEVERITY_MAP_CANTINA = {
    "CRITICAL": "Critical",
    "HIGH": "High",
    "MEDIUM": "Medium",
    "LOW": "Low",
    "INFO": "Informational",
}


def _map_severity(severity: str, platform: str) -> str:
    """Map internal severity to platform-specific severity."""
    maps = {
        "code4rena": SEVERITY_MAP_C4,
        "immunefi": SEVERITY_MAP_IMMUNEFI,
        "cantina": SEVERITY_MAP_CANTINA,
    }
    sev_map = maps.get(platform, {})
    return sev_map.get(severity, severity)


# ---------------------------------------------------------------------------
# Internal markdown report (original format)
# ---------------------------------------------------------------------------
def generate_markdown_report(findings: list[dict], target: str) -> str:
    """Generate the internal markdown audit report (unchanged from v1)."""
    severity_counts = {}
    for f in findings:
        sev = f.get("severity", "INFO")
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    lines = [
        f"# Smart Contract Audit Report",
        f"",
        f"**Target:** `{target}`",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Tool:** Web3 Audit Agents",
        f"",
        f"## Summary",
        f"",
        f"| Severity | Count |",
        f"|----------|-------|",
    ]

    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        count = severity_counts.get(sev, 0)
        if count > 0:
            lines.append(f"| {sev} | {count} |")

    lines.append(f"| **Total** | **{len(findings)}** |")
    lines.append("")

    # Group by severity
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        sev_findings = [f for f in findings if f.get("severity") == sev]
        if not sev_findings:
            continue

        lines.append(f"## {sev} Findings")
        lines.append("")

        for i, f in enumerate(sev_findings, 1):
            lines.append(f"### {sev}-{i:02d}: {f.get('title', 'Untitled')}")
            lines.append("")
            lines.append(f"**Agent:** {f.get('agent', 'Unknown')}")
            if f.get("location"):
                lines.append(f"**Location:** `{f['location']}`")
            lines.append("")
            lines.append(f"**Description:** {f.get('description', '')}")
            lines.append("")
            if f.get("code_snippet"):
                lines.append(f"```solidity")
                lines.append(f"{f['code_snippet']}")
                lines.append(f"```")
                lines.append("")
            if f.get("recommendation"):
                lines.append(f"**Recommendation:** {f['recommendation']}")
                lines.append("")
            lines.append("---")
            lines.append("")

    lines.append("*Generated by Web3 Audit Agents*")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Code4rena format
# ---------------------------------------------------------------------------
def generate_code4rena_report(finding: dict, repo_url: str = "") -> str:
    """Generate a single Code4rena High/Medium submission.

    Code4rena requires INDIVIDUAL submissions for High/Medium findings.
    Low/QA findings should be batched via generate_code4rena_qa_report().

    Args:
        finding: Dict with keys: title, severity, location, description,
                 code_snippet, recommendation, impact, poc, root_cause
        repo_url: GitHub repo URL for the audit (e.g.,
                  "https://github.com/code-423n4/2026-XX-protocol")
    """
    sev = _map_severity(finding.get("severity", "MEDIUM"), "code4rena")
    title = finding.get("title", "Untitled Finding")
    location = finding.get("location", "")
    description = finding.get("description", "")
    impact = finding.get("impact", description)
    code_snippet = finding.get("code_snippet", "")
    recommendation = finding.get("recommendation", "")
    poc = finding.get("poc", "")
    root_cause = finding.get("root_cause", "")

    # Build GitHub permalink
    permalink = ""
    if repo_url and location:
        # Convert "src/Contract.sol:123" -> GitHub URL
        parts = location.split(":")
        file_path = parts[0].replace("\\", "/")
        line = parts[1] if len(parts) > 1 else ""
        permalink = f"{repo_url}/blob/main/{file_path}"
        if line:
            permalink += f"#L{line}"

    lines = []

    # Lines of code
    lines.append("## Lines of code\n")
    if permalink:
        lines.append(permalink)
    else:
        lines.append(f"`{location}`")
    lines.append("")

    # Vulnerability details
    lines.append("## Vulnerability details\n")
    lines.append(f"### Impact\n")
    lines.append(impact)
    lines.append("")

    # Proof of Concept
    lines.append("### Proof of Concept\n")
    if poc:
        lines.append("```solidity")
        lines.append(poc)
        lines.append("```")
    else:
        lines.append("<!-- TODO: Add runnable Foundry PoC -->")
        if code_snippet:
            lines.append("\n**Vulnerable code:**\n")
            lines.append("```solidity")
            lines.append(code_snippet)
            lines.append("```")
    lines.append("")

    # Tools Used
    lines.append("### Tools Used\n")
    lines.append("Manual review, Foundry\n")

    # Recommended mitigation
    lines.append("### Recommended Mitigation Steps\n")
    if root_cause:
        lines.append(f"**Root Cause:** {root_cause}\n")
    lines.append(recommendation)
    lines.append("")

    return "\n".join(lines)


def generate_code4rena_qa_report(findings: list[dict], repo_url: str = "") -> str:
    """Generate a consolidated Code4rena QA report for Low/Info findings.

    Code4rena requires ALL Low and Centralization/Governance findings
    in a single QA report per warden.
    """
    low_findings = [f for f in findings
                    if f.get("severity") in ("LOW", "INFO")]

    lines = ["# QA Report\n"]

    for i, f in enumerate(low_findings, 1):
        sev_prefix = "L" if f.get("severity") == "LOW" else "NC"
        title = f.get("title", "Untitled")
        location = f.get("location", "")
        description = f.get("description", "")
        recommendation = f.get("recommendation", "")

        lines.append(f"## [{sev_prefix}-{i:02d}] {title}\n")
        if location:
            lines.append(f"**Location:** `{location}`\n")
        lines.append(f"{description}\n")
        if recommendation:
            lines.append(f"**Recommendation:** {recommendation}\n")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Immunefi format
# ---------------------------------------------------------------------------
def generate_immunefi_report(finding: dict, contract_address: str = "",
                              chain: str = "Ethereum") -> str:
    """Generate an Immunefi bug bounty submission.

    Immunefi reports go directly to the project team and must include
    a mainnet-fork PoC for High/Critical findings.

    Args:
        finding: Dict with keys: title, severity, location, description,
                 code_snippet, recommendation, impact, poc, root_cause,
                 funds_at_risk, attack_cost, affected_users
        contract_address: Deployed contract address (0x...)
        chain: Target chain name
    """
    sev = _map_severity(finding.get("severity", "MEDIUM"), "immunefi")
    title = finding.get("title", "Untitled Finding")
    description = finding.get("description", "")
    impact = finding.get("impact", description)
    code_snippet = finding.get("code_snippet", "")
    recommendation = finding.get("recommendation", "")
    poc = finding.get("poc", "")
    root_cause = finding.get("root_cause", "")
    funds_at_risk = finding.get("funds_at_risk", "TBD")
    attack_cost = finding.get("attack_cost", "Minimal gas costs")
    affected_users = finding.get("affected_users", "All depositors")

    lines = []
    lines.append(f"# Bug Report: {title}\n")

    # Bug Description
    lines.append("## Bug Description\n")
    lines.append(description)
    if contract_address:
        lines.append(f"\n**Deployed contract:** `{contract_address}` ({chain})")
    lines.append("")

    # Impact
    lines.append("## Impact\n")
    lines.append(f"**Severity: {sev}**\n")
    lines.append(impact)
    lines.append("")
    lines.append("## Risk Breakdown\n")
    lines.append("| Factor | Assessment |")
    lines.append("|--------|-----------|")
    lines.append(f"| Funds at risk | {funds_at_risk} |")
    lines.append(f"| Attack cost | {attack_cost} |")
    lines.append(f"| Affected users | {affected_users} |")
    if contract_address:
        lines.append(f"| Affected contract | `{contract_address}` |")
    lines.append("")

    # Vulnerability Details
    lines.append("## Vulnerability Details\n")
    if root_cause:
        lines.append(f"**Root Cause:** {root_cause}\n")
    if code_snippet:
        lines.append("### Vulnerable Code\n")
        lines.append("```solidity")
        lines.append(code_snippet)
        lines.append("```\n")

    # Proof of Concept
    lines.append("## Proof of Concept\n")
    if poc:
        lines.append("```solidity")
        lines.append(poc)
        lines.append("```")
    else:
        lines.append("<!-- TODO: Add mainnet-fork Foundry PoC -->")
    lines.append("")

    # Recommended Fix
    lines.append("## Recommended Fix\n")
    lines.append(recommendation)
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Cantina format
# ---------------------------------------------------------------------------
def generate_cantina_report(finding: dict, repo_url: str = "") -> str:
    """Generate a Cantina competition submission.

    Args:
        finding: Dict with keys: title, severity, location, description,
                 code_snippet, recommendation, impact, poc, root_cause,
                 attack_path (list of steps)
        repo_url: GitHub repo URL for the competition
    """
    sev = _map_severity(finding.get("severity", "MEDIUM"), "cantina")
    title = finding.get("title", "Untitled Finding")
    location = finding.get("location", "")
    description = finding.get("description", "")
    impact = finding.get("impact", description)
    code_snippet = finding.get("code_snippet", "")
    recommendation = finding.get("recommendation", "")
    poc = finding.get("poc", "")
    root_cause = finding.get("root_cause", "")
    attack_path = finding.get("attack_path", [])

    # Severity prefix
    prefix_map = {"Critical": "C", "High": "H", "Medium": "M", "Low": "L"}
    prefix = prefix_map.get(sev, "M")

    lines = []
    lines.append(f"# [{prefix}-XX] {title}\n")

    # Severity
    lines.append(f"## Severity\n\n**{sev}**\n")

    # Relevant GitHub Links
    lines.append("## Relevant GitHub Links\n")
    if repo_url and location:
        parts = location.split(":")
        file_path = parts[0].replace("\\", "/")
        line = parts[1] if len(parts) > 1 else ""
        link = f"{repo_url}/blob/main/{file_path}"
        if line:
            link += f"#L{line}"
        lines.append(f"- {link}")
    else:
        lines.append(f"- `{location}`")
    lines.append("")

    # Summary
    lines.append("## Summary\n")
    lines.append(description)
    lines.append("")

    # Vulnerability Detail
    lines.append("## Vulnerability Detail\n")
    if root_cause:
        lines.append(f"### Root Cause\n\n{root_cause}\n")
    if code_snippet:
        lines.append("```solidity")
        lines.append(code_snippet)
        lines.append("```\n")
    if attack_path:
        lines.append("### Attack Path\n")
        for i, step in enumerate(attack_path, 1):
            lines.append(f"{i}. {step}")
        lines.append("")

    # Impact
    lines.append("## Impact\n")
    lines.append(impact)
    lines.append("")

    # Proof of Concept
    lines.append("## Proof of Concept\n")
    if poc:
        lines.append("```solidity")
        lines.append(poc)
        lines.append("```")
    else:
        lines.append("<!-- TODO: Add runnable Foundry PoC -->")
    lines.append("")

    # Recommended Mitigation
    lines.append("## Recommended Mitigation\n")
    lines.append(recommendation)
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Pre-submission validation
# ---------------------------------------------------------------------------
def validate_finding_for_submission(finding: dict, platform: str) -> dict:
    """Run pre-submission checks against a finding.

    Returns a dict with:
        - passed: bool (all gate checks passed)
        - score: int (0-100 quality score)
        - issues: list of strings describing problems
        - suggestions: list of strings for improvements
    """
    issues = []
    suggestions = []
    score = 100

    severity = finding.get("severity", "")
    title = finding.get("title", "")
    description = finding.get("description", "")
    poc = finding.get("poc", "")
    impact = finding.get("impact", "")
    recommendation = finding.get("recommendation", "")
    location = finding.get("location", "")
    root_cause = finding.get("root_cause", "")

    # Gate Check 1: Location exists
    if not location:
        issues.append("GATE: Missing location (file and line number)")
        score -= 20

    # Gate Check 2: Has description
    if not description or len(description) < 20:
        issues.append("GATE: Description too short or missing")
        score -= 20

    # Gate Check 3: Severity is set
    if severity not in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"):
        issues.append("GATE: Invalid or missing severity")
        score -= 15

    # Gate Check 4: PoC for High/Critical
    if severity in ("CRITICAL", "HIGH") and not poc:
        issues.append("GATE: High/Critical findings require a runnable PoC")
        score -= 25

    # Gate Check 5: Has recommendation
    if not recommendation:
        issues.append("GATE: Missing recommended mitigation")
        score -= 10

    # Quality: Title quality
    if not title or len(title) < 15:
        suggestions.append("Title too short; use format: [Impact] in [Function] via [Mechanism]")
        score -= 5
    elif len(title) > 100:
        suggestions.append("Title too long (>100 chars); keep under 80")
        score -= 3
    vague_words = ["possible", "potential", "maybe", "might", "could"]
    if any(w in title.lower() for w in vague_words):
        suggestions.append("Title contains vague language; be definitive")
        score -= 5

    # Quality: Impact quantified
    if impact:
        has_dollar = "$" in impact or "USD" in impact or "ETH" in impact
        if not has_dollar:
            suggestions.append("Impact should quantify loss in USD/ETH terms")
            score -= 5
    else:
        suggestions.append("Missing impact section; add with USD quantification")
        score -= 10

    # Quality: Root cause
    if not root_cause:
        suggestions.append("Add explicit root cause for stronger report")
        score -= 5

    # Platform-specific checks
    if platform == "code4rena":
        if severity in ("LOW", "INFO"):
            suggestions.append("Low/Info findings should be in a consolidated QA report, not individual submissions")
    elif platform == "immunefi":
        if severity in ("CRITICAL", "HIGH") and poc and "createSelectFork" not in poc:
            suggestions.append("Immunefi PoC should fork mainnet (use vm.createSelectFork)")
            score -= 5

    passed = not any(issue.startswith("GATE:") for issue in issues)
    score = max(0, score)

    return {
        "passed": passed,
        "score": score,
        "issues": issues,
        "suggestions": suggestions,
    }


# ---------------------------------------------------------------------------
# Dispatcher: generate report for any platform
# ---------------------------------------------------------------------------
def generate_bounty_report(finding: dict, platform: str, **kwargs) -> str:
    """Generate a platform-specific bounty report.

    Args:
        finding: Finding dict with standard keys
        platform: One of "code4rena", "immunefi", "cantina", "internal"
        **kwargs: Platform-specific args (repo_url, contract_address, chain)

    Returns:
        Formatted report string ready for submission
    """
    generators = {
        "code4rena": lambda f: generate_code4rena_report(f, kwargs.get("repo_url", "")),
        "immunefi": lambda f: generate_immunefi_report(
            f, kwargs.get("contract_address", ""), kwargs.get("chain", "Ethereum")),
        "cantina": lambda f: generate_cantina_report(f, kwargs.get("repo_url", "")),
    }

    generator = generators.get(platform)
    if generator:
        return generator(finding)

    # Default: internal format (wrap single finding in a list)
    return generate_markdown_report([finding], kwargs.get("target", "unknown"))


# ---------------------------------------------------------------------------
# Batch report generation
# ---------------------------------------------------------------------------
def generate_all_bounty_reports(findings: list[dict], platform: str,
                                 output_dir: str = "reports", **kwargs) -> list[str]:
    """Generate individual reports for each High/Critical finding,
    plus a consolidated QA report for Low/Info findings.

    Returns list of output file paths.
    """
    os.makedirs(output_dir, exist_ok=True)
    output_files = []
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Separate High/Critical (individual) from Low/Info (consolidated)
    high_findings = [f for f in findings
                     if f.get("severity") in ("CRITICAL", "HIGH", "MEDIUM")]
    low_findings = [f for f in findings
                    if f.get("severity") in ("LOW", "INFO")]

    # Generate individual reports for High/Critical/Medium
    for i, finding in enumerate(high_findings, 1):
        sev = finding.get("severity", "UNKNOWN")
        report = generate_bounty_report(finding, platform, **kwargs)

        # Validate
        validation = validate_finding_for_submission(finding, platform)
        if not validation["passed"]:
            header = f"<!-- VALIDATION FAILED: {'; '.join(validation['issues'])} -->\n\n"
            report = header + report
        elif validation["suggestions"]:
            header = f"<!-- SUGGESTIONS: {'; '.join(validation['suggestions'])} -->\n\n"
            report = header + report

        filename = f"{sev}-{i:02d}_{platform}_{timestamp}.md"
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)
        output_files.append(filepath)

    # Generate consolidated QA report for Low/Info
    if low_findings and platform == "code4rena":
        qa_report = generate_code4rena_qa_report(low_findings,
                                                  kwargs.get("repo_url", ""))
        filename = f"QA-report_{platform}_{timestamp}.md"
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(qa_report)
        output_files.append(filepath)

    return output_files


def generate_json_report(findings: list[dict], target: str) -> str:
    """Generate a JSON audit report."""
    report = {
        "target": target,
        "date": datetime.now().isoformat(),
        "tool": "Web3 Audit Agents",
        "total_findings": len(findings),
        "severity_counts": {},
        "findings": findings,
    }
    for f in findings:
        sev = f.get("severity", "INFO")
        report["severity_counts"][sev] = report["severity_counts"].get(sev, 0) + 1

    return json.dumps(report, indent=2)
